### ISSUE TITLE
driver.findElement throwing 'org.openqa.selenium.WebDriverException' exception instead of ElementNotFoundException, when element not found

### ISSUE THREAD

**Issue by sravanmedarapu** [appium/appium-uiautomator2-driver#27]
**Problem Statement:**
AppiumDriver should throw **`ElementNotFoundException`** when element not found, but using **uiautomator2** as **AUTOMATION_NAME** throwing `org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement` excepton

stack trace:

```
org.openqa.selenium.WebDriverException: Returned value cannot be converted to WebElement: {sessionId=1bca122e-cbb4-4351-84f6-a15db454c4cd, value=No element found, status=7}
Build info: version: '2.53.0', revision: '35ae25b1534ae328c771e0856c93e187490ca824', time: '2016-03-15 10:43:46'
System info: host: 'PRINHYLTPDL0701', ip: '192.168.180.1', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_65'
Driver info: driver.version: AndroidDriver
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:370)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:67)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementById(RemoteWebDriver.java:413)
	at io.appium.java_client.DefaultGenericMobileDriver.findElementById(DefaultGenericMobileDriver.java:75)
	at io.appium.java_client.AppiumDriver.findElementById(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElementById(AndroidDriver.java:1)
	at org.openqa.selenium.By$ById.findElement(By.java:218)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:355)
	at io.appium.java_client.DefaultGenericMobileDriver.findElement(DefaultGenericMobileDriver.java:63)
	at io.appium.java_client.AppiumDriver.findElement(AppiumDriver.java:1)
	at io.appium.java_client.android.AndroidDriver.findElement(AndroidDriver.java:1)

```

**Observations on Execution flow:**
All requests will be processed through [`mjsonwp`](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/mjsonwp/mjsonwp.js#L168)

- **appium-android-driver execution flow:**
All requests will be processed through bootstrap.js [Promise](https://github.com/appium/appium-android-bootstrap/blob/master/lib/bootstrap.js#L108) and promise will be rejected if the status code is not equal to 0 (i.e [!==0](https://github.com/appium/appium-android-bootstrap/blob/master/lib/bootstrap.js#L125) )

- **appium-uiautomator2-driver execution flow**
requests can be proceed in two ways, 

   - by mjsonwp.js [`doJwpProxy `](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/mjsonwp/mjsonwp.js#L188) 

   - jsonwp-proxy's proxy.js [command](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/jsonwp-proxy/proxy.js#L121) and will returns [`resBody.value`](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/jsonwp-proxy/proxy.js#L131) if (`response.statusCode === 200 && resBody.status === 0`) and [`resBody`](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/jsonwp-proxy/proxy.js#L133) if `(response.statusCode === 200)`
**Note:** end points listed in [`NO_PROXY`](https://github.com/sravanmedarapu/appium-uiautomator2-driver/blob/5005d9f19b8cd30775d99734949ef6fbeebd17bc/lib/driver.js#L30) only processed through jsonwp-proxy's proxy.js and rest of all will be processed through [`doJwpProxy `](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/mjsonwp/mjsonwp.js#L188) 

**Investigated result for the issue:**

- FindElement will be processed through jsonwp-proxy's [proxy.js](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/jsonwp-proxy/proxy.js#L121).

- returns  [`resBody`](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/jsonwp-proxy/proxy.js#L133) to [`mjsonwp's driverRes`](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/mjsonwp/mjsonwp.js#L225) when element not found.
**example:** On Element not found ( [return resBody](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/jsonwp-proxy/proxy.js#L133) )
`{"sessionId":"d3804100-c422-4abf-98ae-ce77e1a019fd","status":7,"value":"No element found"}`

    **Note:** if element found `driverRes `would be ([return resBody.value](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/jsonwp-proxy/proxy.js#L131) )
`{"ELEMENT":"f1eaffae-4d89-434d-ae5b-f74299e1c261"}`

- mjsonwp creates `httpResBody` object from `driveRes `( [`httpResBody.status`] (https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/mjsonwp/mjsonwp.js#L249), [`httpResBody.value = driverRes`](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/mjsonwp/mjsonwp.js#L250), [`httpResBody.sessionId = newSessionId`](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/mjsonwp/mjsonwp.js#L270) )
and `httpResBody` looks like this 
example:
```
{
	"sessionId": "d3804100-c422-4abf-98ae-ce77e1a019fd",
	"status": 0,
	"value": {
		"sessionId": "d3804100-c422-4abf-98ae-ce77e1a019fd",
		"status": 7,
		"value": "No element found"
	}
}
```

and [`httpResBody`](https://github.com/appium/appium-base-driver/blob/48dc4965d775bb26e0604f56aea4b1984df5fd2d/lib/mjsonwp/mjsonwp.js#L275) will be sent to java-client's httpmodules. 

- [RemoteWebDriver](https://github.com/SeleniumHQ/selenium/blob/cc6b93571b2ce8f4af9100df34f31acdee3bd7a3/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java#L377) receives `response `as 
```
(Response: SessionID: 9cb53962-d5f3-48b8-b432-24d39e704bc5, Status: 0,
 Value: {sessionId=d3804100-c422-4abf-98ae-ce77e1a019fd, value=No element found, status=7})
```
converts `response's value` to `WebElement` throws `ClassCastException` and selenium throwing 

[`  [WebDriverException("Returned value cannot be converted to WebElement: " + value, ex);]`](https://github.com/SeleniumHQ/selenium/blob/cc6b93571b2ce8f4af9100df34f31acdee3bd7a3/java/client/src/org/openqa/selenium/remote/RemoteWebDriver.java#L384)

**Comment by sravanmedarapu** [comment]
https://github.com/appium/appium-base-driver/pull/63

Using appium-base-driver v2.0.12 should fix this issue

**Comment by sravanmedarapu** [comment]
https://github.com/appium/appium-base-driver/pull/66
