### ISSUE TITLE
`app` can't be blank Error even when browserName is set as `Chrome`

### ISSUE THREAD

**Issue by WasiqB** [appium/appium-uiautomator2-driver#665]
# Description

After upgrading `uiautomator2` driver to version `2.31.2`, I started getting the following Error:

```shell
2023-10-15 16:29:54:307 [AppiumDriver@8235] Encountered internal error running command: SessionNotCreatedError: A new session could not be created. Details: 'app' can't be blank
2023-10-15 16:29:54:307 [AppiumDriver@8235]     at AndroidUiautomator2Driver.createSession (/Users/wasiqbhamla/.nvm/versions/node/v18.18.0/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/driver.ts:273:13)
2023-10-15 16:29:54:307 [AppiumDriver@8235]     at AndroidUiautomator2Driver.createSession (/Users/wasiqbhamla/.appium/node_modules/appium-uiautomator2-driver/lib/driver.ts:244:75)
2023-10-15 16:29:54:308 [AppiumDriver@8235]     at AppiumDriver.createSession (/Users/wasiqbhamla/.nvm/versions/node/v18.18.0/lib/node_modules/appium/lib/appium.js:374:56)
2023-10-15 16:29:54:308 [AppiumDriver@8235]     at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Following is the capabilities I used:

```json
{
  "browserName": "chrome",
  "platformName": "ANDROID",
  "appium:automationName": "UIAutomator2",
  "appium:avd": "Pixel_7_Pro",
  "appium:avdLaunchTimeout": 120000,
  "appium:avdReadyTimeout": 60000,
  "appium:clearDeviceLogsOnStart": true,
  "appium:clearSystemFiles": true,
  "appium:deviceName": "Pixel_7_Pro",
  "appium:fullReset": false,
  "appium:isHeadless": true,
  "appium:noReset": true,
  "appium:platformVersion": "11",
  "appium:systemPort": 8202,
  "appium:uiautomator2ServerInstallTimeout": 60000,
  "appium:uiautomator2ServerLaunchTimeout": 60000
}
```

## Note

This feature was working fine in version `2.29.10`

## Reference

Appium server logs attached as [appium-android-server-1.log](https://github.com/appium/appium-uiautomator2-driver/files/12912250/appium-android-server-1.log)

**Comment by saikrishna321** [comment]
@WasiqB Try 2.31.3

**Comment by WasiqB** [comment]
> @WasiqB Try 2.31.3

Sure, will try this and update here.

**Comment by WasiqB** [comment]
@saikrishna321 , it's working with latest version. You can close this ticket.
