### ISSUE TITLE
Failed to create session. An unknown server-side error occurred while processing the command. 

### ISSUE THREAD

**Issue by HUSBRO150** [appium/appium-uiautomator2-driver#742]
Error
Failed to create session. An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s 7TD5T21402009689 install -r --no-incremental C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
![image](https://github.com/appium/appium-uiautomator2-driver/assets/104379197/bb2e97ba-3ee0-4683-8083-37669a84d4fd)

the follow is server log
C:\Users\mayn>appium --base-path /wd/hub
[Appium] Welcome to Appium v2.5.1
[Appium] Non-default server args:
[Appium] {
[Appium]   basePath: '/wd/hub'
[Appium] }
[Appium] The autodetected Appium home path: C:\Users\mayn\.appium
[Appium] Attempting to load driver uiautomator2...
[Appium] Requiring driver at C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[Appium] AndroidUiautomator2Driver has been successfully loaded in 0.387s
[Appium] Appium REST http interface listener started on http://0.0.0.0:4723/wd/hub
[Appium] You can provide the following URLs in your client code to connect to this server:
[Appium]        http://192.168.238.1:4723/wd/hub
[Appium]        http://192.168.58.1:4723/wd/hub
[Appium]        http://192.168.3.12:4723/wd/hub
[Appium]        http://127.0.0.1:4723/wd/hub (only accessible from the same host)
[Appium] Available drivers:
[Appium]   - uiautomator2@3.0.0 (automationName 'UiAutomator2')
[Appium] No plugins have been installed. Use the "appium plugin" command to install the one(s) you want to use.
[HTTP] --> POST /wd/hub/session
[HTTP] {"capabilities":{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"12","appium:appPackage":"com.tencent.mm","appium:appActivity":".ui.LauncherUI","appium:automationName":"UiAutomator2","appium:deviceName":"NOH-AN01","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]},"desiredCapabilities":{"platformName":"Android","appium:platformVersion":"12","appium:appPackage":"com.tencent.mm","appium:appActivity":".ui.LauncherUI","appium:automationName":"UiAutomator2","appium:deviceName":"NOH-AN01","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true}}
[AppiumDriver@900f] Calling AppiumDriver.createSession() with args: [{"platformName":"Android","appium:platformVersion":"12","appium:appPackage":"com.tencent.mm","appium:appActivity":".ui.LauncherUI","appium:automationName":"UiAutomator2","appium:deviceName":"NOH-AN01","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},null,{"alwaysMatch":{"platformName":"Android","appium:platformVersion":"12","appium:appPackage":"com.tencent.mm","appium:appActivity":".ui.LauncherUI","appium:automationName":"UiAutomator2","appium:deviceName":"NOH-AN01","appium:ensureWebviewsHavePages":true,"appium:nativeWebScreenshot":true,"appium:newCommandTimeout":3600,"appium:connectHardwareKeyboard":true},"firstMatch":[{}]}]
[AppiumDriver@900f] Event 'newSessionRequested' logged at 1708095635619 (23:00:35 GMT+0800 (中国标准时间))
[Appium] Attempting to find matching driver for automationName 'UiAutomator2' and platformName 'Android'
[Appium] The 'uiautomator2' driver was installed and matched caps.
[Appium] Will require it at C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver
[Appium] Requiring driver at C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\build\index.js
[AppiumDriver@900f] Appium v2.5.1 creating new AndroidUiautomator2Driver (v3.0.0) session
[AppiumDriver@900f] Checking BaseDriver versions for Appium and AndroidUiautomator2Driver
[AppiumDriver@900f] Appium's BaseDriver version is 9.5.2
[AppiumDriver@900f] AndroidUiautomator2Driver's BaseDriver version is 9.5.2
[AndroidUiautomator2Driver@d13f] Creating session with W3C capabilities: {
[AndroidUiautomator2Driver@d13f]   "alwaysMatch": {
[AndroidUiautomator2Driver@d13f]     "platformName": "Android",
[AndroidUiautomator2Driver@d13f]     "appium:platformVersion": "12",
[AndroidUiautomator2Driver@d13f]     "appium:appPackage": "com.tencent.mm",
[AndroidUiautomator2Driver@d13f]     "appium:appActivity": ".ui.LauncherUI",
[AndroidUiautomator2Driver@d13f]     "appium:automationName": "UiAutomator2",
[AndroidUiautomator2Driver@d13f]     "appium:deviceName": "NOH-AN01",
[AndroidUiautomator2Driver@d13f]     "appium:ensureWebviewsHavePages": true,
[AndroidUiautomator2Driver@d13f]     "appium:nativeWebScreenshot": true,
[AndroidUiautomator2Driver@d13f]     "appium:newCommandTimeout": 3600,
[AndroidUiautomator2Driver@d13f]     "appium:connectHardwareKeyboard": true
[AndroidUiautomator2Driver@d13f]   },
[AndroidUiautomator2Driver@d13f]   "firstMatch": [
[AndroidUiautomator2Driver@d13f]     {}
[AndroidUiautomator2Driver@d13f]   ]
[AndroidUiautomator2Driver@d13f] }
[AndroidUiautomator2Driver@d13f] The following provided capabilities were not recognized by this driver:
[AndroidUiautomator2Driver@d13f]   connectHardwareKeyboard
[AndroidUiautomator2Driver@d13f (a1e55946)] Session created with session id: a1e55946-30d5-4075-8d92-8b537772ee85
[ADB] Found 1 'build-tools' folders under 'D:\android-sdk-windows' (newest first):
[ADB]     D:\android-sdk-windows\build-tools\29.0.3
[ADB] Using 'adb.exe' from 'D:\android-sdk-windows\platform-tools\adb.exe'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 start-server'
[AndroidUiautomator2Driver@d13f (a1e55946)] Retrieving device list
[ADB] Trying to find connected Android devices
[ADB] Getting connected devices
[ADB] Connected devices: [{"udid":"7TD5T21402009689","state":"device"}]
[AndroidUiautomator2Driver@d13f (a1e55946)] Looking for a device with Android '12.0.0'
[ADB] Setting device id to 7TD5T21402009689
[ADB] Getting device platform version
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 12
[AndroidUiautomator2Driver@d13f (a1e55946)] Using device: 7TD5T21402009689
[ADB] Using 'adb.exe' from 'D:\android-sdk-windows\platform-tools\adb.exe'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 start-server'
[ADB] Setting device id to 7TD5T21402009689
[AndroidUiautomator2Driver@d13f (a1e55946)] Starting 'com.tencent.mm' directly on the device
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell getprop ro.build.version.sdk'
[ADB] Current device property 'ro.build.version.sdk': 31
[ADB] Getting device platform version
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell getprop ro.build.version.release'
[ADB] Current device property 'ro.build.version.release': 12
[ADB] Device API level: 31
[AndroidUiautomator2Driver@d13f (a1e55946)] Relaxing hidden api policy
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell 'settings put global hidden_api_policy_pre_p_apps 1;settings put global hidden_api_policy_p_apps 1;settings put global hidden_api_policy 1''
[AndroidUiautomator2Driver@d13f (a1e55946)] No app sent in, not parsing package/activity
[AndroidUiautomator2Driver@d13f (a1e55946)] Pushing settings apk to the device...
[ADB] Getting package info for 'io.appium.settings'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell dumpsys package io.appium.settings'
[ADB] The version name of the installed 'io.appium.settings' is greater or equal to the application version name ('5.7.5' >= '5.7.5')
[ADB] There is no need to install/upgrade 'C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\io.appium.settings\apks\settings_apk-debug.apk'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell dumpsys activity services io.appium.settings'
[AndroidUiautomator2Driver@d13f (a1e55946)] io.appium.settings is already running. There is no need to reset its permissions.
[Logcat] Starting logs capture with command: D:\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s 7TD5T21402009689 logcat -v threadtime
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell appops set io.appium.settings android:mock_location allow'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell "[ -e '/data/local/tmp/mock_apps.json' ] && echo __PASS__"'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell cat /data/local/tmp/mock_apps.json'
[AndroidUiautomator2Driver@d13f (a1e55946)] Forwarding UiAutomator2 Server port 6790 to local port 8201
[ADB] Forwarding system: 8201 to device: 6790
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 forward tcp:8201 tcp:6790'
[AndroidUiautomator2Driver@d13f (a1e55946)] No app capability. Assuming it is already on the device
[ADB] Getting install status for com.tencent.mm
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell pm path com.tencent.mm'
[ADB] Checking app cert for C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v7.0.0.apk
[ADB] Checking app cert for C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk
[ADB] Using 'apksigner.jar' from 'D:\android-sdk-windows\build-tools\29.0.3\lib\apksigner.jar'
[ADB] Starting apksigner: 'D:\\Program Files\\Java\\jdk1.8.0_101\\bin\\java.exe' -Xmx1024M -Xss1m -jar D:\\android-sdk-windows\\build-tools\\29.0.3\\lib\\apksigner.jar verify --print-certs C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk
[ADB] Starting apksigner: 'D:\\Program Files\\Java\\jdk1.8.0_101\\bin\\java.exe' -Xmx1024M -Xss1m -jar D:\\android-sdk-windows\\build-tools\\29.0.3\\lib\\apksigner.jar verify --print-certs C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v7.0.0.apk
[ADB] 'com.tencent.mm' is installed
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell am force-stop com.tencent.mm'
[ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[ADB]
[ADB] sha256 hash did match for 'appium-uiautomator2-server-debug-androidTest.apk'
[ADB] 'C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' is signed with the default certificate
[ADB] Getting install status for io.appium.uiautomator2.server.test
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell pm path io.appium.uiautomator2.server.test'
[ADB] 'io.appium.uiautomator2.server.test' is not installed
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell pm clear com.tencent.mm'
[AndroidUiautomator2Driver@d13f (a1e55946)] Performed fast reset on the installed 'com.tencent.mm' application (stop and clear)
[ADB] apksigner stdout: Signer #1 certificate DN: EMAILADDRESS=android@android.com, CN=Android, OU=Android, O=Android, L=Mountain View, ST=California, C=US
[ADB] Signer #1 certificate SHA-256 digest: a40da80a59d170caa950cf15c18c454d47a39b26989d8b640ecd745ba71bf5dc
[ADB] Signer #1 certificate SHA-1 digest: 61ed377e85d386a8dfee6b864bd85b0bfaa5af81
[ADB] Signer #1 certificate MD5 digest: e89b158e4bcf988ebd09eb83f5378e87
[ADB]
[ADB] sha256 hash did match for 'appium-uiautomator2-server-v7.0.0.apk'
[ADB] 'C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v7.0.0.apk' is signed with the default certificate
[ADB] Getting package info for 'io.appium.uiautomator2.server'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell dumpsys package io.appium.uiautomator2.server'
[ADB] The version name of the installed 'io.appium.uiautomator2.server' is greater or equal to the application version name ('7.0.0' >= '7.0.0')
[AndroidUiautomator2Driver@d13f (a1e55946)] Server packages status: [{"wasSigned":true,"installState":"sameVersionInstalled","appPath":"C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-v7.0.0.apk","appId":"io.appium.uiautomator2.server"},{"wasSigned":true,"installState":"notInstalled","appPath":"C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk","appId":"io.appium.uiautomator2.server.test"}]
[AndroidUiautomator2Driver@d13f (a1e55946)] Server packages are going to be (re)installed
[AndroidUiautomator2Driver@d13f (a1e55946)] Full packages reinstall is going to be performed
[ADB] Uninstalling io.appium.uiautomator2.server
[ADB] Getting install status for io.appium.uiautomator2.server
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell pm path io.appium.uiautomator2.server'
[ADB] Uninstalling io.appium.uiautomator2.server.test
[ADB] Getting install status for io.appium.uiautomator2.server.test
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell pm path io.appium.uiautomator2.server.test'
[ADB] 'io.appium.uiautomator2.server' is installed
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell am force-stop io.appium.uiautomator2.server'
[ADB] 'io.appium.uiautomator2.server.test' is not installed
[ADB] io.appium.uiautomator2.server.test was not uninstalled, because it was not present on the device
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 uninstall io.appium.uiautomator2.server'
[ADB] 'adb uninstall io.appium.uiautomator2.server' command output: Success
[ADB] io.appium.uiautomator2.server was successfully uninstalled
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 version'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 features'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 help'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 help'
[ADB] The application at 'C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v7.0.0.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 install -r --no-incremental C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-v7.0.0.apk'
[ADB] The application at 'C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' will not be cached, because the device under test has confirmed the support of streamed installs
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 install -r --no-incremental C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk'
[ADB] The installation of 'appium-uiautomator2-server-v7.0.0.apk' took 7618ms
[ADB] Install command stdout: Performing Streamed Install
[ADB] Success
[AndroidUiautomator2Driver@d13f (a1e55946)] Deleting UiAutomator2 session
[AndroidUiautomator2Driver@d13f (a1e55946)] Deleting UiAutomator2 server session
[AndroidUiautomator2Driver@d13f (a1e55946)] Matched '/' to command name 'deleteSession'
[AndroidUiautomator2Driver@d13f (a1e55946)] Did not get confirmation UiAutomator2 deleteSession worked; Error was: UnknownError: An unknown server-side error occurred while processing the command. Original error: Trying to proxy a session command without session id
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell dumpsys activity services io.appium.settings/.recorder.RecorderService'
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell am force-stop com.tencent.mm'
[Logcat] Stopping logcat capture
[ADB] Removing forwarded port socket connection: 8201
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 forward --remove tcp:8201'
[AndroidUiautomator2Driver@d13f (a1e55946)] Restoring hidden api policy to the device default configuration
[ADB] Running 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 shell 'settings delete global hidden_api_policy_pre_p_apps;settings delete global hidden_api_policy_p_apps;settings delete global hidden_api_policy''
[AppiumDriver@900f] Event 'newSessionStarted' logged at 1708095658511 (23:00:58 GMT+0800 (中国标准时间))
[AppiumDriver@900f] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'D:\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s 7TD5T21402009689 install -r --no-incremental C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
[AppiumDriver@900f]     at Timeout.<anonymous> (C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\teen_process\lib\exec.js:140:19)
[AppiumDriver@900f]     at listOnTimeout (node:internal/timers:573:17)
[AppiumDriver@900f]     at processTimers (node:internal/timers:514:7)
[HTTP] <-- POST /wd/hub/session 500 22908 ms - 1528
[HTTP]

i want to open the application wechat through the appium,but when i start the session ,it appears a problem of timeout. After i modify  the time ,it also didn't work.

**Comment by HUSBRO150** [comment]
![image](https://github.com/appium/appium-uiautomator2-driver/assets/104379197/1c15961f-b8df-4d03-a4c4-5cab525e999f)
Traceback (most recent call last):
  File "D:\PythonProject\appium_test\test.py", line 15, in <module>
    driver = Remote(command_executor='http://127.0.0.1:4723/wd/hub', desired_capabilities=desired_cap)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\appium_test\Lib\site-packages\appium\webdriver\webdriver.py", line 234, in __init__
    super().__init__(
  File "D:\ProgramData\anaconda3\envs\appium_test\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "D:\ProgramData\anaconda3\envs\appium_test\Lib\site-packages\appium\webdriver\webdriver.py", line 324, in start_session
    response = self.execute(RemoteCommand.NEW_SESSION, w3c_caps)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ProgramData\anaconda3\envs\appium_test\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "D:\ProgramData\anaconda3\envs\appium_test\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s 7TD5T21402009689 install -r --no-incremental C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
Stacktrace:
UnknownError: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command 'D:\\android-sdk-windows\\platform-tools\\adb.exe -P 5037 -s 7TD5T21402009689 install -r --no-incremental C:\\Users\\mayn\\.appium\\node_modules\\appium-uiautomator2-driver\\node_modules\\appium-uiautomator2-server\\apks\\appium-uiautomator2-server-debug-androidTest.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
    at getResponseForW3CError (D:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\errors.js:1118:9)
    at asyncHandler (D:\Program Files\nodejs\node_global\node_modules\appium\node_modules\@appium\base-driver\lib\protocol\protocol.js:491:57)

this is my python code ,it also have a problem

**Comment by KazuCocoa** [comment]
What happens when you call the below command directly? For example, a typical case is when the device shows up a security popup and blocks the installation command. Then, you would need to allow that, or configure the device's security/developer preferences.

```
[AppiumDriver@900f] Encountered internal error running command: Error: Error executing adbExec. Original error: 'Command 'D:\android-sdk-windows\platform-tools\adb.exe -P 5037 -s 7TD5T21402009689 install -r --no-incremental C:\Users\mayn\.appium\node_modules\appium-uiautomator2-driver\node_modules\appium-uiautomator2-server\apks\appium-uiautomator2-server-debug-androidTest.apk' timed out after 20000ms'. Try to increase the 20000ms adb execution timeout represented by 'uiautomator2ServerInstallTimeout' capability
```
